version: "3.9"

services:

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: example.com
    env_file:
      - ../../mail/mailserver.env
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ../../mail/mailserver/mail-data:/var/mail
      - ../../mail/mailserver/mail-state:/var/mail-state
      - ../../mail/mailserver/mail-logs:/var/log/mail
      - ../../mail/mailserver/config:/tmp/docker-mailserver
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - mail-net

networks:
  mail-net:
    external: true
