version: "3.9"

services:
  backend:
    build: ./backend
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - /var/www/vendor
      - ./backend:/var/www
    networks:
      - devsecops-net

  frontend:
    build: ./frontend
    container_name: react
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - devsecops-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - devsecops-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: marketplace_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devops
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Database/Tables_Indexes.sql:/docker-entrypoint-initdb.d/1_Tables_Indexes.sql
      - ./Database/SP.sql:/docker-entrypoint-initdb.d/2_SP.sql
      - ./Database/insert.sql:/docker-entrypoint-initdb.d/3_insert.sql
    networks:
      - devsecops-net

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - devsecops-net


networks:
  devsecops-net:
    driver: bridge

volumes:
  mysql_data:
